var modList = [
    { 
        name: "IC2 Classic", 
        versions: [
            { versionNumber: "2.0.0", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.19.2" },
            { versionNumber: "1.5.3.0", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.12.2" },
            { versionNumber: "1.5.3.0", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.12.1" },
            { versionNumber: "1.5.3.0", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.12" },
            { versionNumber: "1.4.0.2", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.10.2" },
            { versionNumber: "1.4.0.1", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.10.2" },
            { versionNumber: "1.4.0.0", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.10.2" },
            { versionNumber: "1.2.3", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.2.0", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.1.9", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.1.8", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.1.7", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.1.6", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.1.5.2", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.1.5.1", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.1.5", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.1.4", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.1.2.3", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.1.2.1", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.1.2", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.0.4", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.0.3", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.0.2", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.0.1", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.2.0.0", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.1.3.7.4.3", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.1.3.7.4", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.1.3.7.3", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
            { versionNumber: "1.1.3.7.2", downloadLink: "https://example.com/download.zip", minecraftVersion: "1.7.10" },
        ],
        author: "IC2 Dev Team", 
        description: "IndustrialCraft Classic (IC2 Classic for Short) is an industrial based mod that adds the Industrial Revolution to Minecraft."
    }
];
